const TOKEN_TYPES = {
  IDENTIFIER: "IDENTIFIER",
  BOOLEAN: "BOOLEAN",
  KEYWORD: "KEYWORD",
  NUMBER: "NUMBER",
  RPAREN: "RPAREN",
  LPAREN: "LPAREN",
  QUOTE: "QUOTE",
};

module.exports = {
  TOKEN_TYPES: TOKEN_TYPES,
};
